### ISSUE TITLE
翻訳追加/修正提案

### ISSUE THREAD

**Issue by nishidayoshikatsu** [Code-for-Yamaguchi/covid19-yamaguchi#211]
## 改善詳細 / Details of Improvement
- 現状は有志の方に翻訳していただいた翻訳のため、翻訳に改善の余地がある可能性があるため、追加/修正提案をどんどんしていっていただきたいです。
※[以前のissue](https://github.com/nishidayoshikatsu/covid19-yamaguchi/issues/196)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nishidayoshikatsu** [comment]
以下の名称について、正式名称への差し替えや修正がないかどうか県庁の方に確認中
> 山口県オープンデータカタログサイト → Yamaguchi Prefecture Open Data Catalog Site
> 山口県広報広聴課 → Yamaguchi Prefecture Public Relations Division
> 山口県感染症情報センター → Yamaguchi Prefecture Surveillance Center of Infectious Disease
> 山口県新型コロナウイルス感染症対策本部 → Yamaguchi Prefecture New Coronavirus Infection Control Headquarters

**Comment by nishidayoshikatsu** [comment]
> in and outside of Yamaguchi Prefecture のところは from Yamaguchi and other prefectures とするか from inside and outside of Yamaguchi Prefecture にするとよいです.
> Combined telephone advice center は Related のほうが良いです。
> symptom はimprove よりも recoverのほうがぴったり来ます。

**Comment by nishidayoshikatsu** [comment]
> 以下の名称について、正式名称への差し替えや修正がないかどうか県庁の方に確認中
> 
> > 山口県オープンデータカタログサイト → Yamaguchi Prefecture Open Data Catalog Site
> > 山口県広報広聴課 → Yamaguchi Prefecture Public Relations Division
> > 山口県感染症情報センター → Yamaguchi Prefecture Surveillance Center of Infectious Disease
> > 山口県新型コロナウイルス感染症対策本部 → Yamaguchi Prefecture New Coronavirus Infection Control Headquarters

回答来ました
> 山口県オープンデータカタログサイト
　Yamaguchi Prefecture Open Data Catalog Website
山口県広報広聴課（修正なし）
　Yamaguchi Prefecture Public Relations Division
山口県感染症情報センター（修正なし）
　Yamaguchi Prefecture Surveillance Center of Infectious Disease
山口県新型コロナウイルス感染症対策本部
　Yamaguchi Prefecture COVID-19 Infection Control Headquarters

**Comment by crispytaffy** [comment]
修正原稿こちらでお願いしますー！

> > in and outside of Yamaguchi Prefecture のところは from Yamaguchi and other prefectures とするか from inside and outside of Yamaguchi Prefecture にするとよいです.
https://yamaguchi.stopcovid19.jp/en/about にある「About this site」
---------------------------------------------
This site is designed to provide up-to-date information on the new coronavirus infection (COVID-19). It was established by volunteers from inside and outside of Yamaguchi Prefecture.
---------------------------------------------

> > Combined telephone advice center は Related のほうが良いです。
メイン左カラム
---------------------------------------------
Related telephone advice center
---------------------------------------------

> > symptom はimprove よりも recoverのほうがぴったり来ます。
https://yamaguchi.stopcovid19.jp/en/flow 一番下の右側
---------------------------------------------
However, if symptoms do not recover, please consult the testing consultation desk or your primary doctor again.
---------------------------------------------
