### ISSUE TITLE
陽性患者の属性にフィルターを追加する

### ISSUE THREAD

**Issue by Tomitomi1021** [Code-for-Yamaguchi/covid19-yamaguchi#224]
## 改善詳細 / Details of Improvement
-ある市で直近に陽性になった患者数を知りたいという需要があるようなので、陽性患者の属性を公表日や居住地などで並べ替えたり、検索できるようにすると良いのではないでしょうか？

## 期待する見せ方・挙動 / Expected behavior
- 患者の属性において、居住地を選択できるようにし、表示する患者の属性を選択した居住地のみに絞れるようにする。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Tomitomi1021** [comment]
Noをソートすると辞書順になってしまう問題があるようです。

**Comment by nishidayoshikatsu** [comment]
現状、居住地を選択できるフィルターをつけたほうがいいという方向で進めている
