### ISSUE TITLE
CONTRIBUTORSの追加

### ISSUE THREAD

**Issue by nishidayoshikatsu** [Code-for-Yamaguchi/covid19-yamaguchi#61]
## 改善詳細 / Details of Improvement
- 本リポジトリに貢献していただいた方のリスト（CONTRIBUTORS.md）を作成する

## 期待する見せ方・挙動 / Expected behavior
- 以下の形式でこのissueにコメントをお願いします！

> * 名前（ニックネーム）：
> * GitHub アカウント：
> * Twitter アカウント：
> * 役割：
> * その他：

**Comment by nishidayoshikatsu** [comment]
@nishidayoshikatsu 

* 名前（ニックネーム）：NSD
* GitHub アカウント：[@nishidayoshikatsu](https://github.com/nishidayoshikatsu)
* Twitter アカウント：[@nsd244](https://twitter.com/nsd244)
* 役割：開発/運用リーダー、県庁とのオープンデータ化交渉
* その他：普段はrobot開発とかいろいろやってます〜

**Comment by paichi81** [comment]
The今更ですが、いちおう足跡を残しておきたく…

```
*   名前: Yukihiko Eda
*   GitHub アカウント:@paichi81
*   役割: Kaizen, その他気づいた点の報告など
```

**Comment by nishidayoshikatsu** [comment]
[All Contributors](https://allcontributors.org/)を使ってContributorを追加します！
定型文
`@all-contributors please add <user> for <emoji>`

絵文字キー
https://allcontributors.org/docs/ja/emoji-key

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @nishidayoshikatsu for projectManagement

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @nishidayoshikatsu for projectManagement

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @nishidayoshikatsu for review

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @nishidayoshikatsu for question

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @nishidayoshikatsu for maintenance

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @nishidayoshikatsu for maintenance

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @nishidayoshikatsu for maintenance

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @nishidayoshikatsu for code

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @paichi81 for code

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @paichi81 for bug

**Comment by watagit** [comment]
@all-contributors please add @watagit for code

**Comment by watagit** [comment]
@all-contributors please add @watagit  for bug

**Comment by atososon** [comment]
@all-contributors please add @atososon for code

**Comment by atososon** [comment]
@all-contributors please add @atososon for bug

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @paichi81 for translation

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @crispytaffy for translation

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @crispytaffy for a11y

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @paichi81 for a11y

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @crispytaffy for data

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @gunsow911 for code, bug

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @Tomitomi1021 for code, bug, translation

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @freshcl for code

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @KeisukeSawa for code, bug

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @Himeyama for bug

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @Himeyama for bug

**Comment by nishidayoshikatsu** [comment]
なんかバグ出てるけど原因わかんない....？（入れ直したら解決するやつかな）
issueたってるけど解決してない...？
https://github.com/all-contributors/all-contributors/issues/445

**Comment by nishidayoshikatsu** [comment]
@all-contributors please add @Himeyama for bug
