### ISSUE TITLE
問い合わせ先一覧ページの作成

### ISSUE THREAD

**Issue by KeisukeSawa** [Code-for-Yamaguchi/covid19-yamaguchi#91]
## 改善詳細 / Details of Improvement
東京都版サイトにあるお問い合わせ先一覧の山口県版を作成する。
項目については要検討

## スクリーンショット / Screenshot
![キャプチャ](https://user-images.githubusercontent.com/21189750/88454038-62c29100-cea7-11ea-97a3-261d9a18944d.PNG)

**Comment by KeisukeSawa** [comment]
@nishidayoshikatsu さん

昨日言うのを忘れていましたが、Labelを付ける権限が私にはないのでLabelに関しては適宜割り振っていただけると幸いです。

**Comment by paichi81** [comment]
サイドナビゲーションにもある[問い合わせ窓口](https://www.pref.yamaguchi.lg.jp/cms/a11000/sodan/koronasoudan.html)を参考に次のようにつくってみました。
ただ24時間対応・土日の対応が、いまひとつ元情報のほうであいまいなので、そのまま書き写していいのか疑問です。
そのまま電話連絡できるようになるのは利点だとおもいますが、県担当者に確認をとったほうがいいかもしれません。

![image](https://user-images.githubusercontent.com/4400857/89119197-37fbbc80-d4e7-11ea-9391-2f456496f552.png)
