### ISSUE TITLE
新型コロナ受診相談窓口相談件数のグラフがCenterに表示されない。

### ISSUE THREAD

**Issue by KeisukeSawa** [Code-for-Yamaguchi/covid19-yamaguchi#94]
## 起こっている問題 / The Problem
NSDさんがおっしゃっていた問題をissue化

新型コロナ受診相談窓口相談件数のグラフがCenterに表示されていない。

## スクリーンショット / Screenshot
![キャプチャ](https://user-images.githubusercontent.com/21189750/88454321-b7670b80-cea9-11ea-880e-9e55ade96cde.PNG)

**Comment by lovechoco** [comment]
@nishidayoshikatsu 
このissueの問題点が今ひとつ分からないのですが、
グラフの下のムダな空白がよくないってことなのでしょうかね？

**Comment by nishidayoshikatsu** [comment]
@lovechoco 
返信遅くなって申し訳ないです。

私個人としての意見ですが、サイトのデザインとして特に相談件数の部分の余白が（pc版の場合）目立っているように感じられるため、それに対して何か改善できないかなあと考えている次第です。
